packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp

minimumReleaseAge: 5760

minimumReleaseAgeExclude:
  - "@better-auth/core@1.6.13"
  - "@better-auth/drizzle-adapter@1.6.13"
  - "@better-auth/kysely-adapter@1.6.13"
  - "@better-auth/memory-adapter@1.6.13"
  - "@better-auth/mongo-adapter@1.6.13"
  - "@better-auth/prisma-adapter@1.6.13"
  - "@better-auth/telemetry@1.6.13"
  - better-auth@1.6.13
  - tsx@4.22.4

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - esbuild
  - prisma
  - unrs-resolver
