packages:
  - apps/*
  - packages/*

catalog:
  # ==== general ====
  "@neondatabase/serverless": ^1.0.2
  "@types/node": ^25.5.0
  # ==== db =====
  # drizzle-orm: ^0.45.1
  # drizzle-kit: ^0.31.10
  drizzle-orm: 1.0.0-beta.18-7eb39f0
  drizzle-kit: 1.0.0-beta.18-7eb39f0
  # ==== tooling ====
  eslint: ^9.39.4
  tsx: ^4.21.0
  typescript: ^6.0.2

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - esbuild
  - prisma
  - unrs-resolver
