-- The bm25 (ParadeDB) "building_search_idx" index originally created here was
-- removed as part of migrating off ParadeDB to plain PostgreSQL. This migration
-- is intentionally a no-op so that the migration history remains intact.
