name: Lint

on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
      - run: yarn sass-lint
