name: Tests

on: [push]

jobs:
  steps:
    - uses: actions/checkout@v1
    - name: install node v12.16
      uses: actions/setup-node@v1
      with:
        node-version: '12.16'
    - run: yarn install
    - run: yarn test:frontend
