name: Check Typescript Types

on: [push]

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install
      - run: yarn tsc
